### ISSUE TITLE
Make it possible to add personal notes for listed profiles

### ISSUE THREAD

**Issue by YorVeX** [sbuggay/vaclist-issues#7]
It would be great if I could take some notes for myself why I added certain accounts or where I encountered them so that it helps me remember it if the acc gets banned weeks later. The comment should be only visible to me.

**Comment by sbuggay** [comment]
This has been added: 
![image](https://user-images.githubusercontent.com/2207110/208240920-8a611477-2247-48e9-b585-670f45394e26.png)
