### ISSUE TITLE
Not able to add profile with number profile ID

### ISSUE THREAD

**Issue by YorVeX** [sbuggay/vaclist-issues#8]
The profile https://steamcommunity.com/id/7659654/ cannot be added (or even opened through vaclist.net) using this URL. Maybe because it has a number where others usually put a name?
If I try the text box shows "Account found" but below it just says "No account found with that Steam ID.".

Accessing the account using it's profile URL with SteamID64 works: https://steamcommunity.com/profiles/76561198452543657

**Comment by YorVeX** [comment]
Another example: https://steamcommunity.com/id/200460554

**Comment by sbuggay** [comment]
Yeah I think it's an issue with the regex I use for input detection. Taking a look now.

**Comment by sbuggay** [comment]
Fixed along with a similar bug where numbers at the beginning of a vanity name would confuse the input guesser. 
![image](https://user-images.githubusercontent.com/2207110/163621192-eaa6a585-65bb-4a8a-b805-18062d2a048a.png)
